== Yet another Gradle plugin to deploy an application to Cloud Foundry.

image:https://travis-ci.org/pivotalservices/ya-cf-app-gradle-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/pivotalservices/ya-cf-app-gradle-plugin"]

The purpose of this plugin is to provide ways to manage an application in the Cloud Foundry Environment - Be able to deploy, update, start/stop/restart, attach/remove routes.

"Yet another" because the authoritative source of Cloud Foundry Gradle plugin is expected to be https://github.com/cloudfoundry/cf-java-client/tree/master/cloudfoundry-gradle-plugin[here]


=== Using the Plugin

Start by looking at a sample project using the plugin https://github.com/bijukunjummen/cf-show-env[here]

==== Details

* Add a buildscript dependency:

[source]
----
buildscript {
	ext {
		cfAppVersion = '1.0.7'
	}
	repositories {
		mavenCentral()
		maven { url "https://oss.sonatype.org/content/repositories/releases" }
		maven { url "https://repo.spring.io/release" }
	}
	dependencies {
		classpath("com.github.pivotalservices:ya-cf-app-gradle-plugin:${cfAppVersion}")
	}
}
----

OR Via the new Gradle plugins mechanism:
[source]
----
plugins {
	id "com.github.pivotalservices.cf-app" version "1.0.7"
}
----

* Apply the plugin and provide the Cloud Foundry details:

[source]
----
apply plugin: 'cf-app'

cfConfig {
	//CF Details
	ccHost = "api.local.pcfdev.io"
	ccUser = "admin"
	ccPassword = "admin"
	org = "pcfdev-org"
	space = "pcfdev-space"

	//App Details
	name = "cf-show-env"
	hostName = "cf-show-env"
	filePath = "build/libs/cf-show-env-0.1.2-SNAPSHOT.jar"
	path = ""
	domain = "local.pcfdev.io"
	instances = 2
	memory = 512

	//Env and services
	buildpack = "https://github.com/cloudfoundry/java-buildpack.git"
	environment = ["JAVA_OPTS": "-Djava.security.egd=file:/dev/./urandom", "SPRING_PROFILES_ACTIVE": "cloud"]
	services  = ["mydb"]
}
----

* Run the task(s):

[source]
----
./gradlew cf-push
----

* Override the values using explicit gradle properties, they follow a `cf.*` pattern:

[source]
----
./gradlew cf-push -Pcf.name=Green -Pcf.hostName=demo-time-temp
----

* There is one task to retrieve the details of an application (cf-get-app-detail).
You can use the plugin the following way, say to retrieve the app url's in a gradle task:

[source]
----
task showAppUrls(dependsOn: "cf-get-app-detail") << {
	print "${project.cfConfig.applicationDetail.urls}"
}
----

Say if you wanted to deploy an app and use the apps url to run an acceptance test against you can define a task alone these lines:

[source]
----
task acceptanceTest(type: Test, dependsOn: "cf-get-app-detail")  {
	doFirst() {
		systemProperty "url", "https://${project.cfConfig.applicationDetail.urls[0]}"
	}
	useJUnit {
		includeCategories 'test.AcceptanceTest'
	}
}
----

NOTE: A sample project demonstrating the plugin is availble https://github.com/bijukunjummen/cf-show-env[here]

=== Using the Plugin for a https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html[Blue-Green] Application Deployment

The plugin natively understands how to perform the steps of a Blue-Green deploy. Just run the following and you should be set for a Blue-Green deploy:

[source]
----
./gradlew cf-push-blue-green
----

You may want to run smoke tests after a new version of the app with a new route is brought up before replacing the existing app,
if so a smoke test dependency can be added in the `build.gradle` file the following way:

[source]
----
"cf-push-blue-green-1"{finalizedBy "test"}
----

and run

[source]
----
./gradlew cf-push-blue-green
----


OR if you prefer writing all the blue-green steps yourself, the following is a rough outline of steps:

* Provide a default set of configuration in your build.gradle file.

* Push the `Blue` app mapping to `demo-time.domain`:
[source]
----
./gradlew cf-push -Pcf.name=Blue -Pcf.hostName=demo-time
----

* Push the `Green` app mapping to `demo-time-temp.domain`:
[source]
----
./gradlew cf-push -Pcf.name=Green -Pcf.hostName=demo-time-temp
----

* Once `Green` is verified, remap the route for `Green`:
[source]
----
./gradlew cf-map-route -Pcf.name=Green -Pcf.hostName=demo-time
----

* Unmap the temporary route for Green:
[source]
----
./gradlew cf-unmap-route -Pcf.name=Green -Pcf.hostName=demo-time-temp
----

* Delete the Blue app:
[source]
----
./gradlew cf-delete-app -Pcf.name=Blue
----

* Delete the temporary route:
[source]
----
./gradlew cf-delete-route -Pcf.hostName=demo-time-temp
----



=== Using the Plugin for a https://github.com/concourse/autopilot[Autopilot] equivalent deployment

The plugin natively understands how to perform the steps of an Autopilot based deploy. Just run the following on the command line:

[source]
----
./gradlew cf-push-autopilot
----

OR if you prefer to write each step of autopilot yourself, these are the rough steps:

* Rename the application to something else
[source]
----
./gradlew cf-rename-app -Pcf.newName=old-app-venerable
----

* Push the application, the source of truth is anything specified in cfConfig closure as described above.
[source]
----
./gradlew cf-push
----

* Delete the old app
[source]
----
./gradlew cf-delete-app -Pcf.name=old-app-venerable
----

=== List of all Tasks
.Tasks
[width="100%",frame="topbot",options="header,footer"]
|================================================================================================
|Task                      |Description
|cf-push                   |Pushes an Application to Cloud Foundry
|cf-delete-app             |Delete an application from Cloud Foundry
|cf-delete-route           |Delete a route from Cloud Foundry
|cf-get-app-detail         |Get the application detail from Cloud Foundry
|cf-map-route              |Add a route for an application
|cf-unmap-route            |Remove an existing route for an application
|cf-rename-app             |Rename an applicaiton
|cf-start-app              |Start an Application
|cf-stop-app               |Stop an Application
|cf-restage-app            |Restage an Application
|cf-restart-app            |Restart an Application
|cf-push-autopilot         |Push with https://github.com/concourse/autopilot[Autopilot] steps
|cf-push-blue-green        |Push with https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html[Blue-Green] steps
|================================================================================================
