== Yet another Gradle plugin to deploy an application to Cloud Foundry.

image:https://travis-ci.org/pivotalservices/cf-push-gradle-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/pivotalservices/cf-push-gradle-plugin"]

"Yet another" because the authoritative source of Cloud Foundry Gradle plugin is https://github.com/cloudfoundry/cf-java-client/tree/master/cloudfoundry-gradle-plugin[here]

=== Using the Plugin

* Add a buildscript dependency:

[source]
----
buildscript {
	ext {
		cfAppVersion = '1.0.0-RC1'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("com.github.pivotalservices:ya-cf-app-gradle-plugin:${cfAppVersion}")
	}
}
----

* Apply the plugin and provide the Cloud Foundry details:

[source]
----
apply plugin: 'cf-app'

cfConfig {
	name = "Blue"
	hostName = "demo-time"
	filePath = "build/libs/cf-show-env-0.1.2-SNAPSHOT.jar"

	ccHost = "api.local.pcfdev.io"
	ccUser = "admin"
	ccPassword = "admin"
	org = "pcfdev-org"
	space = "pcfdev-space"
	domain = "local.pcfdev.io"

	buildpack = "https://github.com/cloudfoundry/java-buildpack.git"
	environment = ["JAVA_OPTS": "-Djava.security.egd=file:/dev/./urandom", "SPRING_PROFILES_ACTIVE": "cloud"]
	services  = ["mydb"]
}
----

* Run the task:

[source]
----
./gradlew cf-push
----

* Override the values using explicit gradle properties, they follow a `cf.*` pattern:

[source]
----
./gradlew cf-push -Pcf.name=Green -Pcf.hostName=demo-time-temp
----


=== Using the Plugin for a Blue-Green Application Deployment

* Provide a default set of configuration along the lines described above

* Push the `Blue` app mapping to `demo-time.domain`:
[source]
----
./gradlew cf-push -Pcf.name=Blue -Pcf.hostName=demo-time
----

* Push the `Green` app mapping to `demo-time-temp.domain`:
[source]
----
./gradlew cf-push -Pcf.name=Green -Pcf.hostName=demo-time-temp
----

* Once `Green` is verified, remap the route for `Green`:
[source]
----
./gradlew cf-map-route -Pcf.name=Green -Pcf.hostName=demo-time
----

* Unmap the temporary route for Green:
[source]
----
./gradlew cf-unmap-route -Pcf.name=Green -Pcf.hostName=demo-time-temp
----

* Delete the Blue app:
[source]
----
./gradlew cf-delete-app -Pcf.name=Blue
----

* Delete the temporary route:
[source]
----
./gradlew cf-delete-route -Pcf.hostName=demo-time-temp
----

=== Using the Plugin for a https://github.com/concourse/autopilot[Autopilot] equivalent deployment

* Rename the application to something else
[source]
----
./gradlew cf-rename-app -Pcf.newName=old-app-venerable
----

* Push the application, the source of truth is anything specified in cfConfig closure as described above.
[source]
----
./gradlew cf-push
----

* Delete the old app
[source]
----
./gradlew cf-delete-app -Pcf.name=old-app-venerable
----
